"""add indexes for performance

Revision ID: 08aa2cb86d1f
Revises: 80ceed9ba92b
Create Date: 2025-12-30 19:06:04.694284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08aa2cb86d1f'
down_revision = '80ceed9ba92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index('ix_booking_hall_id', ['hall_id'], unique=False)
        batch_op.create_index('ix_booking_date', ['date'], unique=False)
        batch_op.create_index('ix_booking_status', ['status'], unique=False)
        batch_op.create_index('ix_booking_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_booking_bid', ['bid'], unique=False)
        batch_op.create_index('ix_booking_client_name', ['client_name'], unique=False)
        batch_op.create_index('ix_booking_phone', ['phone'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_phone')
        batch_op.drop_index('ix_booking_client_name')
        batch_op.drop_index('ix_booking_bid')
        batch_op.drop_index('ix_booking_user_id')
        batch_op.drop_index('ix_booking_status')
        batch_op.drop_index('ix_booking_date')
        batch_op.drop_index('ix_booking_hall_id')
    # ### end Alembic commands ###
