"""add payment fields to booking

Revision ID: 3a941c7c34a2
Revises: 08aa2cb86d1f
Create Date: 2026-01-05 21:00:34.544714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a941c7c34a2'
down_revision = '08aa2cb86d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_booking_bid'))
        batch_op.drop_index(batch_op.f('ix_booking_client_name'))
        batch_op.drop_index(batch_op.f('ix_booking_date'))
        batch_op.drop_index(batch_op.f('ix_booking_hall_id'))
        batch_op.drop_index(batch_op.f('ix_booking_phone'))
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_user_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_hall_id'), ['hall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_bid'), ['bid'], unique=False)
        batch_op.drop_column('total')
        batch_op.drop_column('balance')
        batch_op.drop_column('advance_paid')

    # ### end Alembic commands ###
